ci: improvements from internal yotpo breakproof repo

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,9 @@
 #!/usr/bin/env bash
+# output detailed info on what is being executed
 set -x
+# fail if any commands fail
+set -e
 
-# @see https://askubuntu.com/questions/443560/how-do-i-reset-the-colors-of-my-terminal
-# without this "reset", IntelliJ git console outputs everything in red color
-tput setaf 7
-tput setab 0
 export FORCE_COLOR=1
 
 # Used in the validation script to figure out what are the changed files
